version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employees_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  rest-service:
    build: ./rest-service
    depends_on:
      - db
    ports:
      - "5000:5000"

  ui-app:
    build: ./ui-app
    depends_on:
      - rest-service
    ports:
      - "3000:3000"

volumes:
  db_data:
